# Generated by Django 5.2.6 on 2025-10-24 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_estudiante_apoderado_rut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('especialidad', models.CharField(choices=[('NUT', 'Nutricionista'), ('KIN', 'Kinesiólogo/a'), ('TENS', 'TENS'), ('COORD', 'Coordinador/a'), ('APOYO', 'Apoyo deportivo'), ('TSOC', 'Trabajador/a social'), ('OTRA', 'Otra')], default='OTRA', editable=False, max_length=5)),
                ('piso', models.PositiveSmallIntegerField(choices=[(1, 'Primer piso'), (2, 'Segundo piso')], default=1, editable=False)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('REAL', 'Atendida'), ('REPROG', 'Reprogramada'), ('CANC', 'Cancelada')], default='PEND', max_length=6)),
                ('observacion', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.estudiante')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_pmul', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('especialidad', models.CharField(choices=[('NUT', 'Nutricionista'), ('KIN', 'Kinesiólogo/a'), ('TENS', 'TENS'), ('COORD', 'Coordinador/a'), ('APOYO', 'Apoyo deportivo'), ('TSOC', 'Trabajador/a social'), ('OTRA', 'Otra')], default='OTRA', editable=False, max_length=5)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('FIN', 'Finalizada'), ('SEG', 'En seguimiento')], default='FIN', max_length=3)),
                ('publicar_profesor', models.BooleanField(default=False)),
                ('publicar_coordinador', models.BooleanField(default=True)),
                ('publicar_admin', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='core.estudiante')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_pmul', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichaAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='fichas_adjuntos/')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='pmul.fichaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='ProfesionalPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('NUT', 'Nutricionista'), ('KIN', 'Kinesiólogo/a'), ('TENS', 'TENS'), ('COORD', 'Coordinador/a'), ('APOYO', 'Apoyo deportivo'), ('TSOC', 'Trabajador/a social'), ('OTRA', 'Otra')], default='OTRA', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_pmul', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('piso', models.CharField(blank=True, default='', max_length=20)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre para reservar'), ('RESERV', 'Reservada'), ('CANC', 'Cancelada')], default='LIBRE', max_length=6)),
                ('notas', models.CharField(blank=True, default='', max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('profesional', models.ForeignKey(limit_choices_to={'tipo_usuario': 'PMUL'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inicio'],
                'indexes': [models.Index(fields=['profesional', 'inicio'], name='pmul_dispon_profesi_2d1606_idx')],
                'constraints': [models.UniqueConstraint(fields=('profesional', 'inicio'), name='uniq_prof_slot_inicio')],
            },
        ),
    ]
