# Generated by Django 5.2.6 on 2025-10-18 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atleta', '0001_initial'),
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profesor'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='apoderado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.apoderado'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'tipo_usuario': 'ATLE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistenciaatleta',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='atleta.atleta'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_recibe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.profesor'),
        ),
        migrations.AddField(
            model_name='clase',
            name='sede_deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='core.sededeporte'),
        ),
        migrations.AddField(
            model_name='asistenciaatleta',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='atleta.clase'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='atleta.atleta'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='sede_deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.sededeporte'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaprofesor',
            unique_together={('profesor', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaatleta',
            unique_together={('clase', 'atleta')},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('atleta', 'sede_deporte')},
        ),
    ]
