# Generated by Django 5.2.6 on 2025-10-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='categoria_competida',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='atleta',
            name='club_nombre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atleta',
            name='comuna',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='atleta',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='logro_internacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atleta',
            name='logro_nacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atleta',
            name='pertenece_organizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atleta',
            name='puntaje_o_logro',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
