# Generated by Django 5.2.6 on 2025-10-25 16:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0004_asistenciaatleta_registrada_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistenciaatleta',
            old_name='registrada_en',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='asistenciaatleta',
            old_name='observaciones',
            new_name='justificacion',
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaprofesor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='asistenciaatleta',
            name='registrada_por',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='apoderado',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='categoria_competida',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='club_nombre',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='logro_internacional',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='logro_nacional',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='pertenece_organizacion',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='puntaje_o_logro',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='clase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_profesor', to='atleta.clase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='presente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='deporte',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asistenciaatleta',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_atletas', to='atleta.clase'),
        ),
        migrations.AlterField(
            model_name='asistenciaatleta',
            name='presente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_prof', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='faltas_consecutivas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='tipo_atleta',
            field=models.CharField(choices=[('AR', 'Alto Rendimiento'), ('FD', 'Formación Deportiva')], default='FD', max_length=2),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_atleta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_dictadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clase',
            name='sede_deporte',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='clase',
            name='tema',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='hora_salida',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='horas_trabajadas',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='sede_deporte',
        ),
    ]
