# Generated by Django 5.2.6 on 2025-10-28 02:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0004_asistenciaatleta_registrada_en_and_more'),
        ('core', '0007_alter_planificacion_unique_together_and_more'),
        ('usuarios', '0003_usuario_equipo_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistenciaatleta',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaprofesor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clase',
            name='sede_deporte',
        ),
        migrations.AddField(
            model_name='asistenciaatleta',
            name='justificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clase',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='core.curso'),
        ),
        migrations.AddField(
            model_name='clase',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('ENCU', 'En curso'), ('CERR', 'Cerrada')], default='PEND', max_length=4),
        ),
        migrations.AddField(
            model_name='clase',
            name='fin_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.curso'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20),
        ),
        migrations.AlterField(
            model_name='asistenciaatleta',
            name='atleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='atleta.atleta'),
        ),
        migrations.AlterField(
            model_name='asistenciaatleta',
            name='registrada_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='usuario',
            field=models.OneToOneField(blank=True, limit_choices_to={'tipo_usuario': 'ATLE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clase',
            name='tema',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='asistenciaatleta',
            constraint=models.UniqueConstraint(fields=('clase', 'atleta'), name='uniq_asistencia_atleta_por_clase'),
        ),
        migrations.AddConstraint(
            model_name='asistenciaprofesor',
            constraint=models.UniqueConstraint(fields=('profesor', 'fecha'), name='uniq_asistencia_profesor_fecha'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('atleta', 'curso'), name='uniq_inscripcion_atleta_curso'),
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='sede_deporte',
        ),
    ]
