# Generated by Django 5.2.6 on 2025-11-02 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0005_alter_asistenciaatleta_unique_together_and_more'),
        ('core', '0016_alter_deporte_options_alter_estudiante_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciaatleta',
            options={'ordering': ['-clase__fecha', 'clase_id', 'atleta_id']},
        ),
        migrations.AlterModelOptions(
            name='asistenciaprofesor',
            options={'ordering': ['-fecha', 'profesor_id']},
        ),
        migrations.AlterModelOptions(
            name='atleta',
            options={'ordering': ['rut']},
        ),
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ['-fecha', 'hora_inicio']},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['-fecha', 'atleta_id']},
        ),
        migrations.AddField(
            model_name='clase',
            name='sede_deporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='core.sededeporte'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='core.curso'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
