# Generated by Django 5.2.6 on 2025-10-25 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0005_rename_registrada_en_asistenciaatleta_creado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistenciaatleta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asistenciaatleta',
            name='invitado_contacto',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='asistenciaatleta',
            name='invitado_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='asistenciaatleta',
            name='invitado_rut',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='asistenciaatleta',
            name='justificada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asistenciaatleta',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='asistenciaatleta',
            name='sobre_cupo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asistenciaatleta',
            name='atleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atleta.atleta'),
        ),
        migrations.AlterField(
            model_name='asistenciaatleta',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='atleta.clase'),
        ),
        migrations.AlterField(
            model_name='asistenciaatleta',
            name='presente',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='asistenciaatleta',
            name='justificacion',
        ),
    ]
