# Generated by Django 5.2.6 on 2025-10-26 01:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0006_alter_asistenciaatleta_unique_together_and_more'),
        ('core', '0010_estudiante_apoderado_rut'),
        ('usuarios', '0003_usuario_equipo_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(default='agendada', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.RemoveField(
            model_name='asistenciaatleta',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='asistenciaatleta',
            name='invitado_contacto',
        ),
        migrations.RemoveField(
            model_name='asistenciaatleta',
            name='invitado_nombre',
        ),
        migrations.RemoveField(
            model_name='asistenciaatleta',
            name='invitado_rut',
        ),
        migrations.RemoveField(
            model_name='asistenciaatleta',
            name='justificada',
        ),
        migrations.RemoveField(
            model_name='asistenciaatleta',
            name='sobre_cupo',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='presente',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='sede_deporte',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='deporte',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='asistenciaatleta',
            name='registrada_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='asistenciaatleta',
            name='registrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='horas_trabajadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='atleta',
            name='apoderado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.apoderado'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='categoria_competida',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='atleta',
            name='club_nombre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atleta',
            name='comuna',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='atleta',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='atleta',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='estado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='atleta',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='logro_internacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atleta',
            name='logro_nacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atleta',
            name='pertenece_organizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atleta',
            name='puntaje_o_logro',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='clase',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='core.curso'),
        ),
        migrations.AddField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.curso'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20),
        ),
        migrations.AlterField(
            model_name='asistenciaatleta',
            name='atleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='atleta.atleta'),
        ),
        migrations.AlterField(
            model_name='asistenciaatleta',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profesor'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='faltas_consecutivas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='tipo_atleta',
            field=models.CharField(choices=[('BEC', 'Becado'), ('AR', 'Alto rendimiento')], default='BEC', max_length=3),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'tipo_usuario': 'ATLE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clase',
            name='tema',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='asistenciaatleta',
            constraint=models.UniqueConstraint(fields=('clase', 'atleta'), name='uniq_asistencia_atleta_por_clase'),
        ),
        migrations.AddConstraint(
            model_name='asistenciaprofesor',
            constraint=models.UniqueConstraint(fields=('profesor', 'fecha'), name='uniq_asistencia_profesor_fecha'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('atleta', 'curso'), name='uniq_inscripcion_atleta_curso'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_recibe', to=settings.AUTH_USER_MODEL),
        ),
    ]
