# Generated by Django 5.2.6 on 2025-10-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0007_cita_remove_asistenciaatleta_creado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaatleta',
            name='justificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clase',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('ENCU', 'En curso'), ('CERR', 'Cerrada')], default='PEND', max_length=4),
        ),
        migrations.AddField(
            model_name='clase',
            name='fin_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
