# Generated by Django 5.2.6 on 2025-10-27 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0008_asistenciaatleta_justificado_clase_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='usuario',
            field=models.OneToOneField(blank=True, limit_choices_to={'tipo_usuario': 'ATLE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
