# Generated by Django 5.2.6 on 2025-10-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='equipo_rol',
            field=models.CharField(blank=True, choices=[('KINE', 'Equipo Multidisciplinario - Kinesiólogo(a)'), ('PSIC', 'Equipo Multidisciplinario - Psicólogo(a)'), ('NUTR', 'Equipo Multidisciplinario - Nutricionista'), ('TENS', 'Equipo Multidisciplinario - TENS')], help_text='Solo para usuarios del Equipo Multidisciplinario.', max_length=4, null=True),
        ),
    ]
