# Generated by Django 5.2.6 on 2025-11-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_equipo_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
    ]
