# Generated by Django 5.2.6 on 2025-10-23 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_sede_activa_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={},
        ),
        migrations.RenameField(
            model_name='planificacion',
            old_name='creado_por',
            new_name='autor',
        ),
        # ⚠️ Mantén comentado esto si tu tabla estudiante no tiene 'creado'
        # migrations.RemoveField(
        #     model_name='estudiante',
        #     name='creado',
        # ),

        migrations.AddField(
            model_name='curso',
            name='cupos_espera',
            field=models.PositiveIntegerField(default=0, help_text='Opcional: cupos de lista de espera'),
        ),
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(
                choices=[
                    ('BOR', 'Borrador'),
                    ('PUB', 'Publicado'),
                    ('CER', 'Inscripciones cerradas'),
                    ('ARC', 'Archivado')
                ],
                default='BOR',
                max_length=3
            ),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='permitir_inscripcion_rapida',
            field=models.BooleanField(default=False, help_text='Permitir inscripción rápida del profesor en 1ra clase'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesores_apoyo',
            field=models.ManyToManyField(
                blank=True,
                help_text='Profesores de apoyo (opcional, múltiple)',
                limit_choices_to={'tipo_usuario': 'PROF'},
                related_name='cursos_apoyo',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='categoria_competida',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='club_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='comuna',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='logro_internacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='logro_nacional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pertenece_organizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='puntaje_o_logro',
            field=models.CharField(blank=True, default='', max_length=120),
        ),

        # Primero crea los campos en Planificacion
        migrations.AddField(
            model_name='planificacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='planificaciones/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='curso',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='planificaciones',
                to='core.curso',
            ),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='semana',
            field=models.DateField(blank=True, null=True, help_text='Fecha del lunes de la semana'),
        ),

        # Ahora sí: agrega el unique_together
        migrations.AlterUniqueTogether(
            name='planificacion',
            unique_together={('curso', 'semana')},
        ),

        # Y luego las opciones del modelo
        migrations.AlterModelOptions(
            name='planificacion',
            options={'ordering': ['-semana', '-creado']},
        ),

        migrations.AddField(
            model_name='sede',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='comuna',
            field=models.CharField(blank=True, default='Coquimbo', max_length=80),
        ),
        migrations.AlterField(
            model_name='curso',
            name='horario',
            field=models.CharField(
                blank=True,
                default='',
                help_text='(Deprecado) Ej: Lun y Mié 18:00-19:30. Usar horarios estructurados.',
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name='curso',
            name='lista_espera',
            field=models.BooleanField(default=True, help_text="(Deprecado) Usa 'cupos_espera' en su lugar."),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apoderado_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apoderado_telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='CursoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.curso')),
            ],
            options={
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='planificaciones/versiones/%Y/%m/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='core.planificacion')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='metodologia',
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='nivel_dificultad',
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='nombre',
        ),
    ]
