# Generated by Django 5.2.6 on 2025-10-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_estudiante_options_alter_planificacion_options_and_more'),
        ('core', '0004_add_sede_activa_fix'),
    ]

    operations = [
    ]
