# Generated by Django 5.2.6 on 2025-10-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_estudiante_options_alter_planificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
