# Generated by Django 5.2.6 on 2025-10-28 01:57

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_curso_profesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planificacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apoderado_rut',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='creado',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='publica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='semana_iso',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sede',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='radio_metros',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='comuna',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='planificaciones/'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddIndex(
            model_name='planificacion',
            index=models.Index(fields=['curso', 'semana'], name='core_planif_curso_i_44dc30_idx'),
        ),
        migrations.AddIndex(
            model_name='planificacion',
            index=models.Index(fields=['semana_iso'], name='core_planif_semana__88ced4_idx'),
        ),
        migrations.AddConstraint(
            model_name='planificacion',
            constraint=models.UniqueConstraint(fields=('curso', 'semana'), name='uniq_plan_curso_semana'),
        ),
    ]
