# Generated by Django 5.2.6 on 2025-10-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estudiante_modificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='comentarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='semana_iso',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
