# Generated by Django 5.2.6 on 2025-10-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_planificacion_comentarios_planificacion_publico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planificacion',
            old_name='publico',
            new_name='publica',
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='planificaciones/'),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
