# Generated by Django 5.2.6 on 2025-10-29 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_alter_planificacion_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='audiencia_roles',
            field=models.ManyToManyField(blank=True, related_name='comunicados_por_rol', to='auth.group'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='audiencia_tipo',
            field=models.CharField(choices=[('TODOS', 'Todos'), ('ROLES', 'Tipos de usuario'), ('USUARIOS', 'Usuarios específicos')], default='TODOS', max_length=20),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='audiencia_usuarios',
            field=models.ManyToManyField(blank=True, related_name='comunicados_por_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sede',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sede',
            name='comuna',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
