# Generated by Django 5.2.6 on 2025-10-23 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_publico_planificacion_publica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planificacion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='semana_iso',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AddIndex(
            model_name='planificacion',
            index=models.Index(fields=['curso', 'semana'], name='core_planif_curso_i_44dc30_idx'),
        ),
        migrations.AddIndex(
            model_name='planificacion',
            index=models.Index(fields=['semana_iso'], name='core_planif_semana__88ced4_idx'),
        ),
        migrations.AddConstraint(
            model_name='planificacion',
            constraint=models.UniqueConstraint(fields=('curso', 'semana'), name='uniq_plan_curso_semana'),
        ),
    ]
