# Generated by Django 5.2.6 on 2025-10-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_comunicado_audiencia_roles_comunicado_audiencia_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='audiencia_tipo',
        ),
        migrations.RemoveField(
            model_name='comunicado',
            name='audiencia_usuarios',
        ),
        migrations.AddField(
            model_name='comunicado',
            name='audiencia_codigos',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='audiencia_roles',
            field=models.ManyToManyField(blank=True, related_name='comunicados_dirigidos', to='auth.group'),
        ),
    ]
