# Generated by Django 5.2.6 on 2025-10-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_planificacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apoderado_rut',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
