# Generated by Django 5.2.6 on 2025-10-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='n_emergencia',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número de emergencia'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='prevision',
            field=models.CharField(choices=[('FONASA', 'Fonasa'), ('ISAPRE', 'Isapre'), ('NINGUNA', 'Ninguna')], default='NINGUNA', max_length=20, verbose_name='Previsión de salud'),
        ),
    ]
