# Generated by Django 5.2.6 on 2025-10-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_estudiante_apoderado_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='radio_metros',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
