# Generated by Django 5.2.6 on 2025-10-31 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_estudiante_n_emergencia_estudiante_prevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('comuna', models.CharField(blank=True, default='', max_length=80)),
                ('estado', models.CharField(choices=[('NEW', 'Nueva'), ('CON', 'Contactada'), ('ACE', 'Aceptada'), ('REC', 'Rechazada')], db_index=True, default='NEW', max_length=3)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('origen', models.CharField(blank=True, default='', help_text='Ej: web, feria, derivación', max_length=60)),
                ('deporte_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deporte')),
                ('sede_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sede')),
            ],
            options={
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['estado'], name='core_postul_estado_203af9_idx'), models.Index(fields=['rut'], name='core_postul_rut_b4030c_idx')],
            },
        ),
    ]
