# Generated by Django 5.2.6 on 2025-10-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sede_latitud_sede_longitud_sede_radio_metros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='capacidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sede',
            name='comuna',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='sede',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
