# Generated by Django 5.2.6 on 2025-10-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_sede_capacidad_alter_sede_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sede',
            name='comuna',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sede',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
