# Generated by Django 5.2.6 on 2025-10-31 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_postulacionestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROG', 'Programada'), ('OPEN', 'Abierta'), ('CLOSE', 'Cerrada')], db_index=True, default='PROG', max_length=5)),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, nunca se usará para recepción.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='postulacionestudiante',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones', to='core.registroperiodo'),
        ),
    ]
