# Generated by Django 5.2.6 on 2025-10-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sede_capacidad_alter_sede_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='dirigido_a',
            field=models.CharField(choices=[('TODOS', 'Todos'), ('PROFESORES', 'Profesores'), ('ATLETAS', 'Atletas'), ('APODERADOS', 'Apoderados'), ('MULTIDISCIPLINARIO', 'Equipo Multidisciplinario'), ('COORDINADORES', 'Coordinadores'), ('ADMINISTRADORES', 'Administradores')], default='TODOS', max_length=50),
        ),
    ]
