# Generated by Django 5.2.6 on 2025-10-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_registroperiodo_postulacionestudiante_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='capacidad',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(max_length=240),
        ),
    ]
