# Generated by Django 5.2.6 on 2025-10-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_comunicado_dirigido_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='prevision',
            field=models.CharField(choices=[('FONASA', 'Fonasa'), ('ISAPRE', 'Isapre'), ('NINGUNA', 'Ninguna')], default='NINGUNA', max_length=20, verbose_name='Previsión de salud'),
        ),
    ]
