# Generated by Django 5.2.6 on 2025-10-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_sede_capacidad_alter_sede_direccion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planificacion',
            name='uniq_plan_curso_semana',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apoderado_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apoderado_fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
