# Generated by Django 5.2.6 on 2025-11-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_planificacion_uniq_plan_curso_semana_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deporte',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['apellidos', 'nombres']},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='sededeporte',
            options={'ordering': ['sede__nombre', 'deporte__nombre']},
        ),
        migrations.AlterUniqueTogether(
            name='sededeporte',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sededeporte',
            constraint=models.UniqueConstraint(fields=('sede', 'deporte'), name='uniq_sede_deporte'),
        ),
    ]
