# Generated by Django 5.2.6 on 2025-10-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_estudiante_prevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='n_emergencia',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número de emergencia'),
        ),
    ]
