# Generated by Django 5.2.6 on 2025-11-04 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_deporte_options_alter_estudiante_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('ENCU', 'En curso'), ('CERR', 'Cerrada')], default='PEND', max_length=4)),
                ('inicio_real', models.TimeField(blank=True, null=True)),
                ('fin_real', models.TimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.curso')),
            ],
            options={
                'ordering': ('-fecha', 'curso_id'),
                'unique_together': {('curso', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaCursoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado')], default='P', max_length=1)),
                ('observaciones', models.CharField(blank=True, default='', max_length=255)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.asistenciacurso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_curso', to='core.estudiante')),
            ],
            options={
                'unique_together': {('asistencia', 'estudiante')},
            },
        ),
    ]
