# Generated by Django 5.2.6 on 2025-10-29 03:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_estudiante_n_emergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_curso', to='core.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_cursos', to='core.estudiante')),
            ],
            options={
                'indexes': [models.Index(fields=['estudiante', 'estado'], name='core_inscri_estudia_c38ebd_idx'), models.Index(fields=['curso', 'estado'], name='core_inscri_curso_i_22e7b8_idx')],
                'unique_together': {('estudiante', 'curso')},
            },
        ),
    ]
