# Generated by Django 5.2.6 on 2025-11-05 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_asistenciacurso_asistenciacursodetalle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='planificacion',
            name='core_planif_curso_i_44dc30_idx',
        ),
        migrations.RemoveIndex(
            model_name='planificacion',
            name='core_planif_semana__88ced4_idx',
        ),
        migrations.RemoveIndex(
            model_name='postulacionestudiante',
            name='core_postul_estado_203af9_idx',
        ),
        migrations.RemoveIndex(
            model_name='postulacionestudiante',
            name='core_postul_rut_b4030c_idx',
        ),
        migrations.AlterField(
            model_name='curso',
            name='cupos_espera',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='horario',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='curso',
            name='lista_espera',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='permitir_inscripcion_rapida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesores_apoyo',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_usuario': 'PROF'}, related_name='cursos_apoyo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='semana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroperiodo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
