# Generated by Django 5.2.6 on 2025-10-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_inscripcioncurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(choices=[('FORM', 'Formativo'), ('ALTO', 'Alto Rendimiento')], default='FORM', max_length=4)),
                ('rut', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('comuna', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('n_emergencia', models.CharField(blank=True, max_length=30)),
                ('prevision', models.CharField(choices=[('FONASA', 'Fonasa'), ('ISAPRE', 'Isapre'), ('NINGUNA', 'Ninguna')], default='NINGUNA', max_length=20)),
                ('apoderado_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('apoderado_telefono', models.CharField(blank=True, default='', max_length=30)),
                ('pertenece_organizacion', models.BooleanField(default=False)),
                ('club_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('logro_nacional', models.BooleanField(default=False)),
                ('logro_internacional', models.BooleanField(default=False)),
                ('categoria_competida', models.CharField(blank=True, default='', max_length=80)),
                ('puntaje_o_logro', models.CharField(blank=True, default='', max_length=120)),
                ('motivacion_beca', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('APRO', 'Aprobada'), ('RECH', 'Rechazada')], db_index=True, default='PEND', max_length=4)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso')),
                ('estudiante_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones', to='core.estudiante')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
