# Generated by Django 5.2.6 on 2025-10-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_postulacionestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apoderado_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico del/la tutor(a)'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apoderado_fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento del/la tutor(a)'),
        ),
    ]
