# Generated by Django 5.2.6 on 2025-11-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_planificacion_core_planif_curso_i_44dc30_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
