# Generated by Django 5.2.6 on 2025-10-29 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_estudiante_creado_por_estudiante_temporal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('rut', models.CharField(max_length=12)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('comuna', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('n_emergencia', models.CharField(blank=True, max_length=30)),
                ('prevision', models.CharField(choices=[('FONASA', 'Fonasa'), ('ISAPRE', 'Isapre'), ('NINGUNA', 'Ninguna')], default='NINGUNA', max_length=20, verbose_name='Previsión de salud')),
                ('apoderado_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('apoderado_telefono', models.CharField(blank=True, default='', max_length=30)),
                ('apoderado_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('apoderado_fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('pertenece_organizacion', models.BooleanField(default=False)),
                ('club_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('logro_nacional', models.BooleanField(default=False)),
                ('logro_internacional', models.BooleanField(default=False)),
                ('categoria_competida', models.CharField(blank=True, default='', max_length=80)),
                ('puntaje_o_logro', models.CharField(blank=True, default='', max_length=120)),
                ('motivacion_beca', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobada'), ('REC', 'Rechazada')], db_index=True, default='PEN', max_length=3)),
                ('observacion_gestion', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
