# Generated by Django 5.2.6 on 2025-10-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_solicitudinscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinscripcion',
            name='apoderado_rut',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='RUT del/la tutor(a)'),
        ),
    ]
