# Generated by Django 5.2.6 on 2025-10-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_postulacionestudiante_apoderado_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacionestudiante',
            name='apoderado_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='postulacionestudiante',
            name='apoderado_fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulacionestudiante',
            name='apoderado_rut',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='postulacionestudiante',
            name='motivacion_beca',
            field=models.TextField(blank=True, default='', verbose_name='Motivación del deportista para postular a la beca'),
        ),
    ]
