# Generated by Django 5.2.6 on 2025-10-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_postulacionestudiante_apoderado_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apoderado_rut',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='RUT del/la tutor(a)'),
        ),
    ]
