# Generated by Django 5.2.6 on 2025-10-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_estudiante_apoderado_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_habilitado', models.BooleanField(default=False)),
                ('registro_inicio', models.DateField(blank=True, null=True)),
                ('registro_fin', models.DateField(blank=True, null=True)),
                ('texto_convocatoria', models.CharField(blank=True, default='', max_length=200)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
