# Generated by Django 5.2.6 on 2025-10-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_portalconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portalconfig',
            options={'verbose_name': 'Configuración del portal', 'verbose_name_plural': 'Configuración del portal'},
        ),
        migrations.RemoveField(
            model_name='portalconfig',
            name='registro_habilitado',
        ),
        migrations.AddField(
            model_name='portalconfig',
            name='mostrar_registro',
            field=models.BooleanField(default=False, help_text="Muestra el botón 'Postular en línea'"),
        ),
    ]
