# Generated by Django 5.2.6 on 2025-10-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_portalconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalconfig',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='portalconfig',
            name='mostrar_registro',
        ),
        migrations.AddField(
            model_name='portalconfig',
            name='registro_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portalconfig',
            name='singleton_id',
            field=models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='portalconfig',
            name='texto_convocatoria',
            field=models.TextField(blank=True, default=''),
        ),
    ]
