# Generated by Django 5.2.6 on 2025-10-27 05:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_estudiante_apoderado_rut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTR', 'Entrada'), ('SALI', 'Salida')], max_length=4)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_profesor', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sede')),
            ],
            options={
                'verbose_name': 'Asistencia de profesor',
                'verbose_name_plural': 'Asistencias de profesores',
                'unique_together': {('profesor', 'fecha', 'tipo')},
            },
        ),
    ]
