# Generated by Django 5.2.6 on 2025-10-27 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciaprofesor',
            options={'ordering': ['-fecha', '-hora']},
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaprofesor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistenciaprofesor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_prof', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='tipo',
            field=models.CharField(choices=[('ENT', 'Entrada'), ('SAL', 'Salida')], max_length=3),
        ),
        migrations.AlterModelTable(
            name='asistenciaprofesor',
            table='profesor_asistenciaprofesor',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='asistenciaprofesor',
            name='timestamp',
        ),
    ]
