# Generated by Django 5.2.6 on 2025-10-18 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evaluacion', models.CharField(choices=[('KIN', 'Kinesiología'), ('PSI', 'Psicología'), ('NUT', 'Nutrición'), ('TEN', 'TENS'), ('OTR', 'Otro')], max_length=3)),
                ('fecha', models.DateField()),
                ('resultados', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(blank=True, max_length=50)),
                ('logrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('contenido', models.TextField(blank=True)),
                ('metodologia', models.CharField(blank=True, max_length=150)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('nivel_dificultad', models.CharField(blank=True, max_length=50)),
                ('mes', models.DateField(help_text='Usar el día 1 del mes planificado (ej. 2025-09-01)')),
            ],
        ),
        migrations.CreateModel(
            name='PlanificacionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesario', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=150)),
                ('notas', models.TextField(blank=True)),
                ('confirmada', models.BooleanField(default=False)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atleta.atleta')),
            ],
        ),
    ]
