# Generated by Django 5.2.6 on 2025-09-22 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atleta', '0002_initial'),
        ('evaluaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profesionalmulti'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='atleta.atleta'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.profesionalmulti'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.profesor'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='evaluaciones.planificacion'),
        ),
        migrations.AddField(
            model_name='planificacionmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.material'),
        ),
        migrations.AddField(
            model_name='planificacionmaterial',
            name='planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='evaluaciones.planificacion'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('profesional', 'fecha')},
        ),
    ]
